[package]
name = "singleflight"
version = "0.1.0"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-utils = "0.6"
hashbrown = "0.2"
parking_lot = "0.7"
